# Generated by Django 4.1.7 on 2023-04-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='num_requests',
            field=models.IntegerField(default=0),
        ),
    ]
