# Generated by Django 4.1.7 on 2023-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey_num_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='current_search',
            field=models.JSONField(null=True),
        ),
    ]
